// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRH_D_C6RPW2k5pflsR4iv2REr2lTKbLg',
    appId: '1:908117573117:web:be94a536269d51dd6ead94',
    messagingSenderId: '908117573117',
    projectId: 'project-flutter-utfpr',
    authDomain: 'project-flutter-utfpr.firebaseapp.com',
    storageBucket: 'project-flutter-utfpr.appspot.com',
    measurementId: 'G-KXQDJMR9KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoQyWDKDRKFH_D5hABFET3mYkqKBIphns',
    appId: '1:908117573117:android:bea712dd279ada276ead94',
    messagingSenderId: '908117573117',
    projectId: 'project-flutter-utfpr',
    storageBucket: 'project-flutter-utfpr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb5fb_ctOt0eQjcP25k3EGKNRl7MontxM',
    appId: '1:908117573117:ios:ef1e359a8bb91f2f6ead94',
    messagingSenderId: '908117573117',
    projectId: 'project-flutter-utfpr',
    storageBucket: 'project-flutter-utfpr.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb5fb_ctOt0eQjcP25k3EGKNRl7MontxM',
    appId: '1:908117573117:ios:ef1e359a8bb91f2f6ead94',
    messagingSenderId: '908117573117',
    projectId: 'project-flutter-utfpr',
    storageBucket: 'project-flutter-utfpr.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRH_D_C6RPW2k5pflsR4iv2REr2lTKbLg',
    appId: '1:908117573117:web:3f99898cc3de46496ead94',
    messagingSenderId: '908117573117',
    projectId: 'project-flutter-utfpr',
    authDomain: 'project-flutter-utfpr.firebaseapp.com',
    storageBucket: 'project-flutter-utfpr.appspot.com',
    measurementId: 'G-2HC65B2MMT',
  );
}
